### ISSUE TITLE
Interaction wpackio\enqueue if you have 2 instances .. e.g two plugin using wpackio

### ISSUE THREAD

**Issue by deeppresentation** [swashata/wpackio-enqueue#10]
Hi there,
I got troubled by this issue and I think I found a reason ... at least it works now. 
manifestCache was static ... is there any idea behind that why it is static?

As then it use manifest from different instance .. depend what runs first

Have a great day:)

**Comment by swashata** [comment]
Hi,

You are correct. Right now we have

```php
		if ( ! isset( self::$manifestCache[ $this->outputPath ] ) ) {
			self::$manifestCache[ $this->outputPath ] = [];
		}
		self::$manifestCache[ $this->outputPath ][ $dir ] = $manifest;
		return self::$manifestCache[ $this->outputPath ][ $dir ];
```

To make it work with multiple instances, we need to include `$this->appName`, which should be different for different instances anyway. Something like

```php
		if ( ! isset( self::$manifestCache[ $this->appName ] ) ) {
			self::$manifestCache[ $this->appName ] = [];
		}
		if ( ! isset( self::$manifestCache[ $this->appName ][ $this->outputPath ] ) ) {
			self::$manifestCache[ $this->appName ][ $this->outputPath ] = [];
		}
		self::$manifestCache[ $this->appName ][ $this->outputPath ][ $dir ] = $manifest;
		return self::$manifestCache[ $this->appName ][ $this->outputPath ][ $dir ];
```

Would you be interested in doing a PR?

**Comment by swashata** [comment]
On another thought, I don't see why the variable was static at the first place. We can have an instance variable instead of the static one and the issue should go away.
