### ISSUE TITLE
Using dynamic Imports with a CDN

### ISSUE THREAD

**Issue by derweili** [swashata/wpackio-enqueue#14]
I created the followin issue https://github.com/swashata/wp-webpack-script/issues/1230 on the wp-webpack-script repo but I think it's better located here

### Problem Description
For using CDNs, this variable needs to be set to the CDNs URL instead of the WordPress URL.
The docs already mention this case:

For example, we could very much put all the files inside dist to a CDN, and change publicPath to https://cdn.example.com/path/to/asset/dir.

### Possible Solution
I checked the source code and I think this could easily be solved by adding a filter to the `Enqueue::getUrl()` method before returning the value.

https://github.com/swashata/wpackio-enqueue/blob/8a5604f5ab3bd5f000e503dda02603e15e534d47/inc/Enqueue.php#L398-L400

Any thoughts about that?

**Comment by swashata** [comment]
Yes you are correct. Also along with filtering the output of `getUrl`, I think we can also filter the output of `printPublicPath` for more extensibility.

https://github.com/swashata/wpackio-enqueue/blob/8a5604f5ab3bd5f000e503dda02603e15e534d47/inc/Enqueue.php#L145-L149
