### ISSUE TITLE
get url of an arbitrary image in manifest?

### ISSUE THREAD

**Issue by drdogbot7** [swashata/wpackio-enqueue#4]
For instance if my theme includes a few SVG logos that I want to process with webpack, but then I want to use them in a PHP template, is there a good way to get the URLs from the manifest?

Roots/sage theme had a simple asset_path function that just read the manifest and returned the url.

https://github.com/roots/sage/blob/8.5.4/lib/assets.php

**Comment by swashata** [comment]
Hello,

I think this is already possible. You can get everything from the manifest file using

```php
$manifest = $enqueue->getManifest( 'app' );
```

where `app` is the file-entry from your `wpackio.project.js` file.

More information [here](https://wpack.io/apis/php-api/#instance-api-getmanifest)

Then you simply loop through the manifest or select the asset, then use `getUrl` to get the public URL.

```php
$url = $enqueue->getUrl( $manifest['app/assets/image.png'] );
```

More information [here](https://wpack.io/apis/php-api/#instance-api-geturl)

Let me know if it makes sense.

**Comment by drdogbot7** [comment]
Thanks, that works!

It was all there, I just hadn't put the pieces together.
